local M = {}

function M.get(c)
  return {
    -- Editor UI
    Normal          = { fg = c.fg, bg = c.bg },
    NormalFloat     = { fg = c.fg, bg = c.bg_alt },
    NormalNC        = { fg = c.fg, bg = c.bg },
    FloatBorder     = { fg = c.border, bg = c.bg_alt },
    FloatTitle      = { fg = c.green_bright, bg = c.bg_alt, bold = true },
    ColorColumn     = { bg = c.bg_alt },
    Cursor          = { fg = c.bg, bg = c.green_dark },
    CursorLine      = { bg = c.bg_alt },
    CursorColumn    = { bg = c.bg_alt },
    CursorLineNr    = { fg = c.green_bright, bold = true },
    LineNr          = { fg = c.fg_dim },
    SignColumn      = { bg = c.bg },
    VertSplit       = { fg = c.bg_highlight },
    WinSeparator    = { fg = c.bg_highlight },
    Folded          = { fg = c.fg_dim, bg = c.bg_alt },
    FoldColumn      = { fg = c.fg_dim, bg = c.bg },
    Visual          = { bg = c.bg_highlight },
    VisualNOS       = { bg = c.bg_highlight },
    Search          = { fg = c.bg, bg = c.green_bright },
    IncSearch       = { fg = c.bg, bg = c.green_lime },
    CurSearch       = { fg = c.bg, bg = c.green_lime, bold = true },
    MatchParen      = { fg = c.green_lime, bold = true, underline = true },
    Pmenu           = { fg = c.fg, bg = c.bg_alt },
    PmenuSel        = { fg = c.fg_bright, bg = c.bg_highlight, bold = true },
    PmenuSbar       = { bg = c.bg_alt },
    PmenuThumb      = { bg = c.bg_highlight },
    StatusLine      = { fg = c.fg_bright, bg = c.bg_alt },
    StatusLineNC    = { fg = c.fg_dim, bg = c.bg_alt },
    TabLine         = { fg = c.gray, bg = c.bg_alt },
    TabLineFill     = { bg = c.bg_alt },
    TabLineSel      = { fg = c.white, bg = c.bg, bold = true },
    WinBar          = { fg = c.fg, bg = c.bg, bold = true },
    WinBarNC        = { fg = c.fg_dim, bg = c.bg },
    Title           = { fg = c.green_bright, bold = true },
    Directory       = { fg = c.blue_bright },
    NonText         = { fg = c.fg_dim },
    Whitespace      = { fg = c.bg_highlight },
    SpecialKey      = { fg = c.fg_dim },
    EndOfBuffer     = { fg = c.bg },
    Conceal         = { fg = c.fg_dim },
    QuickFixLine    = { bg = c.bg_highlight },
    WildMenu        = { fg = c.bg, bg = c.green_bright },
    ModeMsg         = { fg = c.green_bright, bold = true },
    MsgArea         = { fg = c.fg, bg = c.bg },
    ErrorMsg        = { fg = c.red, bold = true },
    WarningMsg      = { fg = c.yellow },
    MoreMsg         = { fg = c.green_bright },
    Question        = { fg = c.green_bright },

    -- Syntax
    Comment         = { fg = c.comment, italic = true },
    Constant        = { fg = c.blue_light },
    String          = { fg = c.green },
    Character       = { fg = c.green },
    Number          = { fg = c.blue_light },
    Boolean         = { fg = c.blue_light, bold = true },
    Float           = { fg = c.blue_light },
    Identifier      = { fg = c.fg_bright },
    Function        = { fg = c.green_bright },
    Statement       = { fg = c.blue_bright },
    Conditional     = { fg = c.blue_bright },
    Repeat          = { fg = c.blue_bright },
    Label           = { fg = c.blue },
    Operator        = { fg = c.blue_light },
    Keyword         = { fg = c.blue_bright, italic = true },
    Exception       = { fg = c.blue_bright, bold = true },
    PreProc         = { fg = c.green_olive },
    Include         = { fg = c.blue_accent },
    Define          = { fg = c.green_olive },
    Macro           = { fg = c.green_olive },
    PreCondit       = { fg = c.green_olive },
    Type            = { fg = c.blue },
    StorageClass    = { fg = c.blue_bright },
    Structure       = { fg = c.blue },
    Typedef         = { fg = c.blue },
    Special         = { fg = c.green_bright },
    SpecialChar     = { fg = c.green_lime },
    Tag             = { fg = c.blue_bright },
    Delimiter       = { fg = c.fg },
    SpecialComment  = { fg = c.gray, italic = true },
    Debug           = { fg = c.red },
    Underlined      = { underline = true },
    Ignore          = { fg = c.fg_dim },
    Error           = { fg = c.red, bold = true },
    Todo            = { fg = c.bg, bg = c.green_lime, bold = true },

    -- Diff
    DiffAdd         = { fg = c.green_bright, bg = c.bg_alt },
    DiffChange      = { fg = c.blue_bright, bg = c.bg_alt },
    DiffDelete      = { fg = c.red, bg = c.bg_alt },
    DiffText        = { fg = c.green_lime, bg = c.bg_highlight, bold = true },
    diffAdded       = { fg = c.green_bright },
    diffRemoved     = { fg = c.red },
    diffChanged     = { fg = c.blue_bright },
    diffFile        = { fg = c.blue_light, bold = true },
    diffLine        = { fg = c.comment },

    -- Spell
    SpellBad        = { sp = c.red, undercurl = true },
    SpellCap        = { sp = c.blue_bright, undercurl = true },
    SpellLocal      = { sp = c.blue, undercurl = true },
    SpellRare       = { sp = c.magenta, undercurl = true },

    -- Diagnostics
    DiagnosticError          = { fg = c.red },
    DiagnosticWarn           = { fg = c.yellow },
    DiagnosticInfo           = { fg = c.blue_bright },
    DiagnosticHint           = { fg = c.green_bright },
    DiagnosticOk             = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo  = { sp = c.blue_bright, undercurl = true },
    DiagnosticUnderlineHint  = { sp = c.green_bright, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.bg_alt },
    DiagnosticVirtualTextWarn  = { fg = c.yellow, bg = c.bg_alt },
    DiagnosticVirtualTextInfo  = { fg = c.blue_bright, bg = c.bg_alt },
    DiagnosticVirtualTextHint  = { fg = c.green_bright, bg = c.bg_alt },

    -- LSP
    LspReferenceText         = { bg = c.bg_highlight },
    LspReferenceRead         = { bg = c.bg_highlight },
    LspReferenceWrite        = { bg = c.bg_highlight, bold = true },
    LspSignatureActiveParameter = { fg = c.green_lime, bold = true },
    LspCodeLens              = { fg = c.comment, italic = true },
    LspInlayHint             = { fg = c.fg_dim, bg = c.bg_alt, italic = true },

    -- Treesitter
    ["@comment"]             = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.gray, italic = true },
    ["@comment.todo"]        = { link = "Todo" },
    ["@comment.error"]       = { fg = c.red, bold = true },
    ["@comment.warning"]     = { fg = c.yellow, bold = true },
    ["@comment.note"]        = { fg = c.blue_light, bold = true },
    ["@string"]              = { link = "String" },
    ["@string.escape"]       = { fg = c.green_lime },
    ["@string.special"]      = { fg = c.green_lime },
    ["@string.regexp"]       = { fg = c.blue_light },
    ["@character"]           = { link = "Character" },
    ["@number"]              = { link = "Number" },
    ["@boolean"]             = { link = "Boolean" },
    ["@float"]               = { link = "Float" },
    ["@constant"]            = { fg = c.blue_light },
    ["@constant.builtin"]    = { fg = c.blue_light, italic = true },
    ["@constant.macro"]      = { fg = c.green_olive },
    ["@variable"]            = { fg = c.fg_bright },
    ["@variable.builtin"]    = { fg = c.blue_light, italic = true },
    ["@variable.parameter"]  = { fg = c.fg, italic = true },
    ["@variable.member"]     = { fg = c.blue_light },
    ["@property"]            = { fg = c.blue_light },
    ["@field"]               = { fg = c.blue_light },
    ["@function"]            = { link = "Function" },
    ["@function.builtin"]    = { fg = c.green_bright, italic = true },
    ["@function.call"]       = { fg = c.green_bright },
    ["@function.macro"]      = { fg = c.green_olive },
    ["@function.method"]     = { fg = c.green_bright },
    ["@function.method.call"] = { fg = c.green_bright },
    ["@constructor"]         = { fg = c.blue },
    ["@keyword"]             = { link = "Keyword" },
    ["@keyword.function"]    = { fg = c.blue_bright, italic = true },
    ["@keyword.return"]      = { fg = c.blue_bright, italic = true, bold = true },
    ["@keyword.operator"]    = { fg = c.blue_bright },
    ["@keyword.import"]      = { fg = c.blue_accent },
    ["@keyword.conditional"] = { fg = c.blue_bright },
    ["@keyword.repeat"]      = { fg = c.blue_bright },
    ["@keyword.exception"]   = { fg = c.blue_bright, bold = true },
    ["@operator"]            = { link = "Operator" },
    ["@type"]                = { link = "Type" },
    ["@type.builtin"]        = { fg = c.blue, italic = true },
    ["@type.definition"]     = { fg = c.blue, bold = true },
    ["@attribute"]           = { fg = c.green_olive },
    ["@module"]              = { fg = c.blue_light },
    ["@namespace"]           = { fg = c.blue_light },
    ["@label"]               = { link = "Label" },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.special"] = { fg = c.green_lime },
    ["@tag"]                 = { fg = c.blue_bright },
    ["@tag.attribute"]       = { fg = c.green_bright },
    ["@tag.delimiter"]       = { fg = c.fg_dim },

    -- Markup
    ["@markup.heading"]      = { fg = c.green_bright, bold = true },
    ["@markup.heading.1"]    = { fg = c.green_lime, bold = true },
    ["@markup.heading.2"]    = { fg = c.green_bright, bold = true },
    ["@markup.heading.3"]    = { fg = c.green, bold = true },
    ["@markup.heading.4"]    = { fg = c.green_olive, bold = true },
    ["@markup.strong"]       = { bold = true },
    ["@markup.italic"]       = { italic = true },
    ["@markup.underline"]    = { underline = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.link"]         = { fg = c.blue_light, underline = true },
    ["@markup.link.url"]     = { fg = c.blue_light, underline = true },
    ["@markup.link.label"]   = { fg = c.blue_bright },
    ["@markup.raw"]          = { fg = c.green },
    ["@markup.quote"]        = { fg = c.gray, italic = true },
    ["@markup.list"]         = { fg = c.blue_bright },

    -- Git signs
    GitSignsAdd    = { fg = c.green_bright },
    GitSignsChange = { fg = c.blue_bright },
    GitSignsDelete = { fg = c.red },

    -- Telescope
    TelescopeNormal       = { fg = c.fg, bg = c.bg_alt },
    TelescopeBorder       = { fg = c.border, bg = c.bg_alt },
    TelescopePromptNormal = { fg = c.fg_bright, bg = c.bg_highlight },
    TelescopePromptBorder = { fg = c.bg_highlight, bg = c.bg_highlight },
    TelescopePromptTitle  = { fg = c.bg, bg = c.green_bright, bold = true },
    TelescopePreviewTitle = { fg = c.bg, bg = c.blue_bright, bold = true },
    TelescopeResultsTitle = { fg = c.bg_alt, bg = c.bg_alt },
    TelescopeSelection    = { fg = c.fg_bright, bg = c.bg_highlight, bold = true },
    TelescopeMatching     = { fg = c.green_lime, bold = true },

    -- NvimTree / Neo-tree
    NvimTreeNormal          = { fg = c.fg, bg = c.bg_alt },
    NvimTreeFolderIcon      = { fg = c.blue_bright },
    NvimTreeFolderName      = { fg = c.blue_bright },
    NvimTreeOpenedFolderName = { fg = c.green_bright, bold = true },
    NvimTreeRootFolder      = { fg = c.green_lime, bold = true },
    NvimTreeGitDirty        = { fg = c.yellow },
    NvimTreeGitNew          = { fg = c.green_bright },
    NvimTreeGitDeleted      = { fg = c.red },
    NvimTreeSpecialFile     = { fg = c.blue_light, underline = true },
    NvimTreeIndentMarker    = { fg = c.fg_dim },

    -- WhichKey
    WhichKey        = { fg = c.green_bright },
    WhichKeyGroup   = { fg = c.blue_bright },
    WhichKeyDesc    = { fg = c.fg_bright },
    WhichKeySeparator = { fg = c.comment },
    WhichKeyFloat   = { bg = c.bg_alt },

    -- Notify / noice
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder  = { fg = c.yellow },
    NotifyINFOBorder  = { fg = c.blue_bright },
    NotifyDEBUGBorder = { fg = c.comment },
    NotifyTRACEBorder = { fg = c.magenta },
    NotifyERRORIcon   = { fg = c.red },
    NotifyWARNIcon    = { fg = c.yellow },
    NotifyINFOIcon    = { fg = c.blue_bright },
    NotifyERRORTitle  = { fg = c.red, bold = true },
    NotifyWARNTitle   = { fg = c.yellow, bold = true },
    NotifyINFOTitle   = { fg = c.blue_bright, bold = true },
  }
end

return M
